package router

import (
	"os"

	"github.com/gin-gonic/gin"
	"github.com/minipanel/minipanel/internal/api"
	"github.com/minipanel/minipanel/internal/middleware"
)

func NewRouter() *gin.Engine {
	r := gin.New()
	// 默认不信任任何代理，防止 X-Forwarded-For 伪造绕过 IP 白名单/登录限流
	_ = r.SetTrustedProxies(nil)
	r.Use(middleware.LoggerMiddleware())
	r.Use(gin.Recovery())
	r.Use(middleware.CORSMiddleware())
	r.Use(middleware.BindDomainMiddleware())
	r.Use(middleware.AllowIPsMiddleware())
	r.Use(middleware.SecurityEntranceMiddleware())

	if _, err := os.Stat("static/index.html"); err == nil {
		r.Static("/assets", "static/assets")
		r.StaticFile("/favicon.ico", "static/favicon.ico")
		r.StaticFile("/", "static/index.html")
		r.NoRoute(func(c *gin.Context) {
			c.File("static/index.html")
		})
	}

	auth := api.NewAuthAPI()
	authGroup := r.Group("/api/v1")
	{
		authGroup.POST("/login", auth.Login)
		authGroup.POST("/logout", auth.Logout)
		authGroup.GET("/captcha", auth.Captcha)

		ver := api.NewVersionAPI()
		authGroup.GET("/version", ver.Get)
	}

	apiV1 := r.Group("/api/v1")
	apiV1.Use(middleware.AuthMiddleware())
	{
		dash := api.NewDashboardAPI()
		apiV1.GET("/dashboard", middleware.PermissionMiddleware("/dashboard"), dash.GetInfo)
		apiV1.GET("/dashboard/monitor", middleware.PermissionMiddleware("/monitor"), dash.GetMonitor)

		file := api.NewFileAPI()
		fileGroup := apiV1.Group("/files", middleware.PermissionMiddleware("/files"))
		fileGroup.GET("", file.List)
		fileGroup.GET("/content", file.GetContent)
		fileGroup.POST("", file.Create)
		fileGroup.PUT("", file.Update)
		fileGroup.DELETE("", file.Delete)
		fileGroup.DELETE("/force", file.ForceDelete)
		fileGroup.POST("/upload", file.Upload)
		fileGroup.GET("/download", file.Download)
		fileGroup.POST("/upload-multiple", file.UploadMultiple)
		fileGroup.GET("/download-zip", file.DownloadZip)
		fileGroup.POST("/rename", file.Rename)
		fileGroup.POST("/chmod", file.Chmod)
		fileGroup.POST("/compress", file.Compress)
		fileGroup.POST("/extract", file.Extract)
		fileGroup.POST("/copy", file.Copy)
		fileGroup.POST("/move", file.Move)
		fileGroup.GET("/search", file.Search)
		fileGroup.GET("/recycle-bin", file.ListRecycleBin)
		fileGroup.POST("/recycle-bin/restore", file.RestoreRecycle)
		fileGroup.POST("/recycle-bin/clear", file.ClearRecycleBin)

		term := api.NewTerminalAPI()
		apiV1.GET("/terminal/ws", middleware.PermissionMiddleware("/ssh"), term.HandleWS)

		proc := api.NewProcessAPI()
		apiV1.GET("/processes", middleware.PermissionMiddleware("/processes"), proc.List)
		apiV1.POST("/processes/kill", middleware.PermissionMiddleware("/processes"), proc.Kill)

		ctn := api.NewContainerAPI()
		containerGroup := apiV1.Group("/containers", middleware.PermissionMiddleware("/containers"))
		containerGroup.GET("", ctn.List)
		containerGroup.GET("/:name", ctn.Inspect)
		containerGroup.POST("", ctn.Create)
		containerGroup.POST("/:name/start", ctn.Start)
		containerGroup.POST("/:name/stop", ctn.Stop)
		containerGroup.DELETE("/:name", ctn.Remove)
		containerGroup.GET("/:name/logs", ctn.Logs)
		containerGroup.GET("/:name/files", ctn.ListFiles)
		containerGroup.POST("/pull", ctn.Pull)

		app := api.NewAppAPI()
		appGroup := apiV1.Group("/apps", middleware.PermissionMiddleware("/apps"))
		appGroup.GET("", app.List)
		appGroup.GET("/search", app.Search)
		appGroup.GET("/icon/:key", app.Icon)
		appGroup.GET("/:id", app.Detail)
		appGroup.POST("/install", app.Install)
		appGroup.GET("/install/:name/status", app.InstallStatus)
		appGroup.POST("/:id/uninstall", app.Uninstall)
		appGroup.GET("/installed", app.Installed)
		appGroup.DELETE("/history", app.ClearHistory)
		appGroup.POST("/sync", app.Sync)
		appGroup.GET("/sources", app.Sources)
		appGroup.POST("/sources", app.AddSource)
		appGroup.DELETE("/sources/:id", app.RemoveSource)

		cron := api.NewCronjobAPI()
		cronGroup := apiV1.Group("/cronjobs", middleware.PermissionMiddleware("/cronjobs"))
		cronGroup.GET("", cron.List)
		cronGroup.POST("", cron.Create)
		cronGroup.PUT("/:id", cron.Update)
		cronGroup.DELETE("/:id", cron.Delete)
		cronGroup.POST("/:id/run", cron.Run)

		setting := api.NewSettingAPI()
		settingGroup := apiV1.Group("/settings", middleware.PermissionMiddleware("/settings"))
		settingGroup.GET("", setting.Get)
		settingGroup.PUT("", setting.Update)
		settingGroup.POST("/reset", setting.Reset)
		settingGroup.POST("/clear-data", setting.ClearData)

		update := api.NewUpdateAPI()
		updateGroup := apiV1.Group("/update", middleware.PermissionMiddleware("/settings"))
		updateGroup.GET("/check", update.Check)
		updateGroup.POST("/apply", update.Apply)
		updateGroup.GET("/status", update.Status)
		updateGroup.GET("/log", update.Log)

		monitor := api.NewMonitorAPI()
		monitorGroup := apiV1.Group("/monitor", middleware.PermissionMiddleware("/monitor"))
		monitorGroup.GET("/history", monitor.List)
		monitorGroup.GET("/realtime", monitor.GetRealtime)

		apiV1.POST("/auth/change-password", auth.ChangePassword)

		audit := api.NewAuditAPI()
		apiV1.GET("/audit-logs", middleware.PermissionMiddleware("/logs"), audit.List)

		logAPI := api.NewLogAPI()
		apiV1.GET("/logs", middleware.PermissionMiddleware("/logs"), logAPI.List)

		website := api.NewWebsiteAPI()
		websiteGroup := apiV1.Group("/websites", middleware.PermissionMiddleware("/websites"))
		websiteGroup.GET("", website.List)
		websiteGroup.GET("/nginx/status", website.GetNginxStatus)
		websiteGroup.POST("/nginx/start", website.StartNginx)
		websiteGroup.POST("/nginx/stop", website.StopNginx)
		websiteGroup.POST("/nginx/restart", website.RestartNginx)
		websiteGroup.POST("/nginx/reload", website.ReloadNginx)
		websiteGroup.POST("", website.Create)
		websiteGroup.GET("/:id", website.GetByID)
		websiteGroup.PUT("/:id", website.Update)
		websiteGroup.DELETE("/:id", website.Delete)
		websiteGroup.PUT("/:id/toggle", website.Toggle)
		websiteGroup.GET("/:id/logs", website.GetAccessLogs)
		websiteGroup.GET("/:id/traffic", website.GetTrafficStats)
		websiteGroup.GET("/:id/databases", website.ListDatabasesByWebsite)
		apiV1.GET("/databases/:id/websites", middleware.PermissionMiddleware("/websites"), website.ListWebsitesByDB)

		php := api.NewPhpAPI()
		phpGroup := apiV1.Group("/php", middleware.PermissionMiddleware("/websites"))
		phpGroup.GET("/versions", php.GetVersions)
		phpGroup.POST("/versions/install", php.InstallVersion)
		phpGroup.DELETE("/versions/:version", php.RemoveVersion)
		phpGroup.POST("/versions/:version/start", php.StartFpm)
		phpGroup.POST("/versions/:version/stop", php.StopFpm)
		phpGroup.POST("/versions/:version/restart", php.RestartFpm)
		phpGroup.GET("/versions/:version/extensions", php.GetExtensions)
		phpGroup.POST("/versions/:version/extensions", php.InstallExtension)
		phpGroup.DELETE("/versions/:version/extensions/:name", php.RemoveExtension)
		phpGroup.GET("/versions/:version/config", php.GetPhpIni)
		phpGroup.PUT("/versions/:version/config", php.UpdatePhpIni)
		phpGroup.GET("/versions/:version/socket", php.GetFpmSocket)

		db := api.NewDatabaseAPI()
		dbGroup := apiV1.Group("/databases", middleware.PermissionMiddleware("/databases"))
		dbGroup.GET("", db.List)
		dbGroup.POST("", db.Create)
		dbGroup.PUT("/:id", db.Update)
		dbGroup.DELETE("/:id", db.Delete)
		dbGroup.POST("/test", db.TestConnection)
		dbGroup.GET("/:id/dbs", db.ListDatabases)
		dbGroup.GET("/:id/tables", db.ListTables)
		dbGroup.POST("/:id/create-db", db.CreateDatabase)
		dbGroup.POST("/:id/create-user", db.CreateUser)
		dbGroup.DELETE("/:id/dbs/:dbName", db.DropDatabase)
		dbGroup.DELETE("/:id/users/:username", db.DropUser)
		dbGroup.GET("/:id/tables/:dbName/:tableName", db.DescribeTable)
		dbGroup.POST("/:id/query", db.ExecuteQuery)
		dbGroup.POST("/:id/backup/:dbName", db.Backup)
		dbGroup.POST("/:id/restore/:dbName", db.Restore)

		fw := api.NewFirewallAPI()
		fwGroup := apiV1.Group("/firewall", middleware.PermissionMiddleware("/firewall"))
		fwGroup.GET("/rules", fw.List)
		fwGroup.GET("/rules/deleted", fw.ListDeletedRules)
		fwGroup.POST("/rules", fw.Create)
		fwGroup.PUT("/rules/:id", fw.Update)
		fwGroup.DELETE("/rules/:id", fw.Delete)
		fwGroup.POST("/rules/:id/restore", fw.RestoreRule)
		fwGroup.POST("/rules/clear-deleted", fw.ClearDeletedRules)
		fwGroup.POST("/apply", fw.Apply)
		fwGroup.GET("/status", fw.Status)
		fwGroup.POST("/start", fw.Start)
		fwGroup.POST("/stop", fw.Stop)
		fwGroup.GET("/diagnose", fw.Diagnose)
		fwGroup.GET("/live-rules", fw.LiveRules)
		fwGroup.POST("/insert", fw.InsertRule)
		fwGroup.DELETE("/live-rule", fw.DeleteLiveRule)
		fwGroup.POST("/lockdown", fw.Lockdown)

		backup := api.NewBackupAPI()
		backupGroup := apiV1.Group("/backups", middleware.PermissionMiddleware("/backups"))
		backupGroup.GET("/tasks", backup.ListTasks)
		backupGroup.POST("/tasks", backup.CreateTask)
		backupGroup.PUT("/tasks/:id", backup.UpdateTask)
		backupGroup.DELETE("/tasks/:id", backup.DeleteTask)
		backupGroup.POST("/tasks/:id/run", backup.RunBackup)
		backupGroup.GET("/records", backup.ListRecords)
		backupGroup.DELETE("/records/:id", backup.DeleteRecord)
		backupGroup.POST("/records/:id/restore", backup.RestoreBackup)

		agentAPI := api.NewAgentAPI()
		// Agent 工具具备 Shell/文件/数据库等 root 级能力，仅管理员可用
		agentGroup := apiV1.Group("/agent", middleware.PermissionMiddleware("/agent"), middleware.AdminMiddleware())
		agentAPI.RegisterRoutes(agentGroup)

		sysAPI := api.NewSystemAPI()
		sysGroup := apiV1.Group("/system/services", middleware.PermissionMiddleware("/settings"))
		sysGroup.GET("", sysAPI.CheckServices)
		sysGroup.POST("/:name/install", sysAPI.InstallService)
		sysGroup.POST("/:name/start", sysAPI.StartService)
		sysGroup.POST("/:name/stop", sysAPI.StopService)
		sysGroup.POST("/:name/restart", sysAPI.RestartService)

		user := api.NewUserAPI()
		adminV1 := apiV1.Group("/")
		adminV1.Use(middleware.AdminMiddleware())
		{
			adminV1.GET("/users/features", user.ListFeatures)
			adminV1.GET("/users", user.List)
			adminV1.POST("/users", user.Create)
			adminV1.PUT("/users/:id", user.Update)
			adminV1.POST("/users/:id/reset-password", user.ResetPassword)
			adminV1.DELETE("/users/:id", user.Delete)
		}
	}

	return r
}
